# Use root/example as user/password credentials
version: '3.7'

services:
  composer:
    image: composer
  npm:
    image: npm
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: usernamae
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27018:27017
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: usernamae
      ME_CONFIG_MONGODB_ADMINPASSWORD: password